
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-12-08T07:52:56+1300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5dd3c785991ec991974c53cd0b1058281a2f872f",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
